Feature/PIP-366
Hycom-PIP/pip2020-back pull request #26
Opened 2020-04-09 14:06 UTC by Szpilka007

Implementacja testów integracyjnych

2020-04-13 05:32 UTC, BinaryIgor requested changes

2020-04-13 05:32 UTC, Iprogrammerr commented on integration-tests/pom.xml
>      <version>0.0.1</version>
Tutuaj mieliśmy profil, fullTests, który odpalał nam testy integracyjne, tylko jeżeli był aktywny. Przywrócić:)

2020-04-13 05:32 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/controller/tests/karateAuthorization.json
> +{
Zrobiłbym raczej plik z konfiguracją(karateConfiguration.json). Tam mielibyśmy adminUser, adminPassword i baseUrl. Autoryzowalibyśmy się tak: https://stackoverflow.com/questions/51244771/how-to-implement-basic-auth-using-karate

2020-04-14 16:23 UTC, Szpilka007 commented on integration-tests/pom.xml
>      <version>0.0.1</version>
Ten profil był na developie :D , nie znalazł nie u mnie w kodzie bo jeszcze nie mergowałem mojej branchy z developem :D

2020-04-15 04:47 UTC, BinaryIgor requested changes
1.Usuńmy jeszcze stare, przykładowe testy, a więc sample.feature i SampleTest.
2.Zostańmy przy nazwie paczki integration.tests.
3.Zmieńmy nazwę na AdminAuthorizationTest i adminAuthorization.feature. Zmieńmy też odpowiednio opisy scenariuszy w adminAuthorization.feature.
4.Robimy tak dlatego, że testy integracyjne są pod scenariusze i funkcjonalności, a nie pod konkretny kod:)

2020-04-15 04:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/karate-config.js
> +        uncorrectPassword: 'Admin123*pip+2020',
Teraz się zorientowałem, że słowo uncorrect nie istnieje, zamieńmy więc na incorrectPassword:)
Podobnie mamy w adminController.feature

2020-04-15 04:47 UTC, Iprogrammerr commented on pom.xml
> +                <version>${karate-junit.version}</version>
Tutaj zróbmy karate.version jako jednego propertasa, bo chcemy mieć te wersje zsynchronizowane:)

2020-04-15 06:53 UTC, merged