Feature/pip 397
Hycom-PIP/pip2020-back pull request #44
Opened 2020-05-13 16:45 UTC by goloneczka

2020-05-14 05:01 UTC, BinaryIgor requested changes

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/AdminAuthorizationTest.java
> +    Karate weatherTests(){
To do nowej klaski - WeatherEndpointsTest

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
> +    public WeatherDbUtils(Map<String, Object> config)  {
Mapka <String, String> nie przejdzie?

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
> +        jooqConfiguration.set(new DataSourceConnectionProvider(new TransactionAwareDataSourceProxy(dataSource)));
Wystarczy nam tutaj sam DataSource, żadnych wielkich rzeczy tu nie robimy

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
> +        jooqConfiguration.set(new DefaultExecuteListenerProvider(new DefaultExecuteListener()));
To nam do niczego niepotrzebne:)

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
> +        countriesRepository.createCountry(new Country("Polska"));
Zmieniłbym na insertData, a dane brał z jsona. Wówczas można też tego jsona wykorzystać do porównań w testach:)

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
> +    public void clearWeatherData() {
Zmieńmy na clear i róbmy po prosu deleteFrom na wszystkich tabelach z Weather

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +Feature: Restaurants Api
Ten pliczek nazwałbym weatherEndpoints.feature. A Feature: Weather Endpoints

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    * header Authorization =  call read('basic-auth.js') {user: #(user), password: #(password)}
Header nam niepotrzebny, endpointy są publiczne:) Testy dla admina jako odzielny feature: adminWeatherEndpoints

2020-05-14 05:01 UTC, BinaryIgor commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    Then status 200
Po udanym create/update/delete sprawdzajmy też getem czy stan się zmienił

2020-05-14 05:01 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +  Scenario: Integration test for update country
Scenariusz myślę, że lepiej jak nazwiemy w konwencji Update country. To że to test to wiemy z kontekstu:)

2020-05-14 05:01 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    And match $ == [{"country": "Polska"},{"country": "countryForDelete"}]
Tutaj bierzmy dane z jsona, który też wykorzystany będzie w klasce od bazy danych

2020-05-14 05:01 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    * header Authorization =  call read('basic-auth.js') {user: #(user), password: #(password)}
header, gdzie będzie potrzebny można wczytać tylko raz jako background:)

2020-05-19 05:18 UTC, BinaryIgor requested changes
Reszta komentarzu na rocketchatcie:)

2020-05-19 05:18 UTC, BinaryIgor commented on integration-tests/pom.xml
> +            <version>2.8.0</version>
jackson, wersja z parent poma. Nie mieszajmy dodatkowej libki:)

2020-05-20 13:47 UTC, BinaryIgor requested changes
1.W pomie mamy sporo niepotrzebnych zależności, wywalmy je
2.Zróbmy porządek w paczkach.
3. Dajmy paczkę weather, a w niej wszystkie jej feature'y, WeatherEndpointsTest(ma literówkę, do aktualizacji będą też ścieżki) i WeatherDbUtils.

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
>          countriesRepository.deleteCountry("Polska");
Truncate/delete wszystkich tabel pogodowych używając DslContext

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    * json jsonCity = read('classpath:weather/cities.json')
cities i forecasts

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
>    Scenario: Integration test for get forecast
O nazwach scenariuszy już mówiliśmy:)

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    * set cityArray[0] = jsonCity
Niepotrzebna zmienna, porównujmy do cities

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    Given path 'forecasts/city/Warszawa'
Nazwę miasta wyciągałbym z jsona

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather.feature
> +    And match $ contains jsonForecast
powinniśmy sprawdzać  ==, zamiast contains. Contains sprawdza tylko czy mamy jeden element taki sam, a nie wszystkie:)

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weatherAdmin.feature
> +    * def db = callonce initDatabase
Zmienne bez przedrostka i wyrażające co jest w środku(citiesUpdate ma cityForUpdate i cityForDelete, to średnio intuicyjne jest)

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weatherAdmin.feature
> +  Scenario: verify inserted country
Nie jako odzielny scenariusz, tylko jak część insert country

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weatherAdmin.feature
> +    * def countryArray = []
Użyjmy po prostu countries, testy modyfikujące mogą wykonywać się potem:)

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weatherAdmin.feature
> +    * set cityArray[0] = jsonCity
Jak powyżej - modyfikacja + sprawdzenie jako jeden scenariusz.

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weatherAdmin.feature
> +    * def cityArray = []
Sprawdzajmy po prostu cities, nie trzeba tworzyć dodatkowej zmiennej

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weatherAdmin.feature
> +  Scenario: delete city
Get sprawdzający usunięcie

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/resources/weather/cities.json
> +{
Skoro cities to albo tablica jedno elementowa, albo city.json. Ale chyba cities wygodniejsze z punktu widzenia używania w testach

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/resources/weather/citiesUpdate.json
> +{
Tu bym dał citiesModification.json. Kluczami niech będzie po prostu update  i delete

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/resources/weather/countries.json
> +{
To samo co w cities:)

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/resources/weather/countriesUpdate.json
> +{
Tak samo jak w cities

2020-05-20 13:47 UTC, Iprogrammerr commented on integration-tests/src/test/resources/weather/forecasts.json
> +{
Tak samo jak w cities/countries:)

2020-05-22 04:51 UTC, BinaryIgor requested changes
w paczce com.pip.chatbot.integration.tests.weather miałbyć feature, klaska testowa i klaska do bazki:)

2020-05-22 04:51 UTC, Iprogrammerr commented on database/src/main/java/com/pip/chatbot/repository/forecast/CountriesRepository.java
> +    public boolean deleteAll(){
To wywalmy z repo, niechcemy żeby inne klasy mogły tak robić:)

2020-05-22 04:51 UTC, Iprogrammerr commented on integration-tests/pom.xml
> -            <scope>test</scope>
Spring-boot starter jeszcze niepotrzebny:)

2020-05-22 04:51 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
>      }
Używajmy do tego celu dslContext, żeby nie trzeba było tworzyć takiej ryzykownej metody w repozytoriach:)

2020-05-22 04:51 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather/weatherAdmin.feature
> +    And request countryModify.countryUpdate
Zróbmy country do inserta, bo to nie jest czytelne, że do insert używamy update, a do update delete

2020-05-22 04:51 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/tests/weather/weatherAdmin.feature
> +    When method POST
To samo z nazewnictwem, co w countries

2020-05-25 13:53 UTC, BinaryIgor reviewed
Paczka weather z wszystkim, co do niej należy, czyli:
- feature'y(w podpaczce features)
- klaski testowe
- klaska utilsowa

2020-05-25 13:53 UTC, Iprogrammerr commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
> +                .execute();
Country chyba też będzie trzeba, bazka musi być pusta

2020-05-25 14:36 UTC, goloneczka commented on integration-tests/src/test/java/com/pip/chatbot/integration/tests/WeatherDbUtils.java
> +                .execute();
bazka jest pozniej pusta. Kaskdadowo sie wszystko usuwa

2020-05-26 13:31 UTC, merged